version: '2'
services:
  db:
    image: mariadb:10.3.36
    container_name: dev-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: "%"
    command: mysqld --sql_mode=""
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    image: dev-web
    container_name: dev-web
    build:
        context: .
        dockerfile: Dockerfile.centos
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/c/Users/Omen/PhpstormProjects/salida_mr:/var/www/salida_mr
      - /mnt/c/Users/Omen/PhpstormProjects/bedford:/var/www/bedford
volumes:
  db_data: